### ISSUE TITLE
borehole dataset

### ISSUE THREAD

**Issue by Benedict-89** [ds4owd-001/project-Benedict-89#1]
@larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Thank you @Benedict-89  for setting up the repository. Can you please work on the following tasks:

- rename your repository to: project-Benedict-89 (see here: https://github.com/ds4owd-001/boreholes-Benedict-89/settings)
- Add the required folder structure (data/raw/ & docs folder)
- Move your data into the data/raw folder
- Create a new Quarto document named index.qmd and store it in docs folder

All details: https://ds4owd-001.github.io/website/assignments/md-05/am-05-1-project-data.html#step-3-create-new-folders

**Comment by larnsce** [comment]
This is looking really great. Thanks for sorting out the items I had listed above.
