### ISSUE TITLE
My Capstone Project

### ISSUE THREAD

**Issue by Benedict-89** [ds4owd-001/project-Benedict-89#2]
@larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
@Benedict-89, thanks for tagging us.

Do you have a specific question about the project? 

I have looked at your folder structure and what I do not yet see are the items that we had asked you to work in in the homework assignment of Module 7. Have a look and let me know if something is unclear:

https://ds4owd-001.github.io/website/assignments/md-07/am-07-2-project-metadata.html

**Comment by Benedict-89** [comment]
@larnsce 
I am trying to work on the items in the homework assignment for Module 7, as you indicated. I tried uploading the dictionary.csv file I created under the processed folder, but the server does not allow me to upload. I get feedback stating, "Unexpected response from server." What should I do to fix this problem?

**Comment by larnsce** [comment]
Thanks @Benedict-89. Can you please share a screenshot?

**Comment by Benedict-89** [comment]
@larnsce 
Thank you. I have fixed the problem
